apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-grafana
  namespace: monitoring
  annotations:
    iam.gke.io/gcp-service-account: eso-grafana-reader@rosy-precinct-477218-u8.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: monitoring
spec:
  provider:
    gcpsm:
      projectID: rosy-precinct-477218-u8
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: eso-grafana
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: grafana-cloud-remote-write
        property: url
    - secretKey: user
      remoteRef:
        key: grafana-cloud-remote-write
        property: user
    - secretKey: token
      remoteRef:
        key: grafana-cloud-remote-write
        property: token
